import React from 'react'
import useAuth from '../../../hooks/useAuth'

export const Home = () => {
  const {auth} = useAuth();
  return (
    <div>
      <h1>Welcome to  Marbust Accounts&reg; 2.5.0</h1>
      <hr />
      {auth && auth.firstName && auth.lastName && (<h2>{auth.firstName + ' ' + auth.lastName}</h2>)}
        <br />
        <ol>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
          <li><strong>Update (Aug 22, 2024):</strong>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti possimus, maxime officia, reiciendis porro quis blanditiis fugit assumenda cum ut distinctio tempora pariatur cupiditate. Nihil dolorum deserunt reiciendis quasi aut.</li>
        </ol>
    </div>
  )
}
